### ISSUE TITLE
Ask

### ISSUE THREAD

**Issue by fahmi182** [eneskaya/google-app-indexing-cordova#1]
Do you have example how to use this plugin? how it works?

**Comment by eneskaya** [comment]
Do you need an implementation example or a use case? 

For the use case part: let's say you have shopping app. When a customer views a product within your app, you can send this view to the Google App Index, e.g. The customer views "Product XYZ from A Special Brand" you would use AppIndexing.startView(...) with the product title, the description, the web path (if applicable) and the android path (android-app://..., refer to documentation). When the customer searches for that product trough the Google search bar later on, he would see the the title you've indexed before in the search results/suggestions and if he clicks it he would be taken to your app and specifically to the page of the product he looked for. 

I will put a more detailed example use case in the documentation. 

Please let me know if you need a quick start guide or a sample app.

**Comment by fahmi182** [comment]
Thanks, appreciate! :)

okay, my website structure is:

homepage: https://www.example.com
article page: https://www.example.com/articles/article-slug-here.html

then, my apps structure is:

homepage: /index.html
article page: /detail.html?id=12345

i mean, how to works with that. thanks again :)

**Comment by mehmetkoc182** [comment]
A sample cordova/phonegap project would be nice.

I've got some questions myself about where exactly these should be called in a phonegap project for android.

AppIndexing.startView(title, description, webPath, androidPath, success, error);
AppIndexing.endView(title, description, webPath, androidPath, success, error);
and maybe examples of each variable in there?

Thanks!
